# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Chutney and Pepper"
description: > # this means to ignore newlines until "email:"
   healthy, simple, wholesome food

email: jacquigodinagh@gmail.com
#blog logo
logo: "/assets/images/Logo_small_noframe-3.png"
# blog cover
cover: "/assets/images/IMG_8770_web.jpg"

name: 'Jacqui Godinagh'
author: 'Jacqui Godinagh'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://chutneyandpepper.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	instagram
    url:	http://instagram.com/_jacquimarie
    desc: Follow me on instagram
    #share_url: http://twitter.com/share
    #share_title: ?text=
    #share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

#  - icon:	github
#    url:	https://github.com/dirkfabisch
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
